version: "3.9"
services:   
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"         
    networks:
      - shopnetwork
  redisinsights:
    image: "redislabs/redisinsight"
    networks:
      - shopnetwork
    ports:
      - "8001:8001"          
networks:
  shopnetwork: